openapi: 3.0.0
info:
  description: retrieve temperature & humidity and compute tests
  title: test API
  version: 0.1.0
servers:
- description: server url from my azure subscription
  url: http://myazure.url.com/api/v1/
paths:
  /data:
    get:
      description: Optional extended description in CommonMark or HTML
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: A json format
      summary: Returns a string with an explanation on how to use this url.
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sensordata'
        description: retrieve (temperature/humidity) value
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sensorefficiency'
          description: A json format
      summary: Compute temperature and humidity stuff.
components:
  schemas:
    sensordata:
      properties:
        temperature:
          maximum: 120
          minimum: -50
          type: number
        humidity:
          maximum: 100
          minimum: 0
          type: number
      required:
      - humidity
      - temperature
    sensorefficiency:
      example:
        value: value
      properties:
        value:
          type: string
      required:
      - value
